services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
    volumes:
      - pgdata:/var/lib/postgresql/data
     
 
volumes:
  pgdata:
